// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ua_parse_
DataFrame ua_parse_(std::vector < std::string > agents, std::string yaml_file_loc);
RcppExport SEXP uaparser_ua_parse_(SEXP agentsSEXP, SEXP yaml_file_locSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type agents(agentsSEXP);
    Rcpp::traits::input_parameter< std::string >::type yaml_file_loc(yaml_file_locSEXP);
    __result = Rcpp::wrap(ua_parse_(agents, yaml_file_loc));
    return __result;
END_RCPP
}
// parse_r_agents_
DataFrame parse_r_agents_(std::vector < std::string > user_agents);
RcppExport SEXP uaparser_parse_r_agents_(SEXP user_agentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type user_agents(user_agentsSEXP);
    __result = Rcpp::wrap(parse_r_agents_(user_agents));
    return __result;
END_RCPP
}
