// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_ua_parse
DataFrame c_ua_parse(std::vector < std::string > agents, std::string yaml_file_loc);
RcppExport SEXP uaparser_c_ua_parse(SEXP agentsSEXP, SEXP yaml_file_locSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::vector < std::string > >::type agents(agentsSEXP );
        Rcpp::traits::input_parameter< std::string >::type yaml_file_loc(yaml_file_locSEXP );
        DataFrame __result = c_ua_parse(agents, yaml_file_loc);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
