# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_ua_parse <- function(agents, yaml_file_loc) {
    .Call('uaparser_c_ua_parse', PACKAGE = 'uaparser', agents, yaml_file_loc)
}

